apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
    - name: http
      port: 8082
  selector:
    app: user-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      containers:
        - name: user-app
          image: com/newisland/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000